<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-16T17:26:13Z" name="Suite" finished-at="2022-10-16T17:26:54Z" duration-ms="40941">
    <groups>
    </groups>
    <test started-at="2022-10-16T17:26:13Z" name="Test" finished-at="2022-10-16T17:26:54Z" duration-ms="40941">
      <class name="pushpa.PushpaValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:pushpa.PushpaValidation@5b04476e]" started-at="2022-10-16T22:56:13Z" name="launchApplication" finished-at="2022-10-16T22:56:19Z" duration-ms="5164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="pushpaValidationWithModifications()[pri:0, instance:pushpa.PushpaValidation@5b04476e]" started-at="2022-10-16T22:56:19Z" name="pushpaValidationWithModifications" finished-at="2022-10-16T22:56:34Z" duration-ms="15632" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pushpaValidationWithModifications -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:pushpa.PushpaValidation@5b04476e]" started-at="2022-10-16T22:56:34Z" name="tearDown" finished-at="2022-10-16T22:56:34Z" duration-ms="153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:pushpa.PushpaValidation@5b04476e]" started-at="2022-10-16T22:56:34Z" name="launchApplication" finished-at="2022-10-16T22:56:38Z" duration-ms="3675" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="pushpaValidationWithoutModifications()[pri:0, instance:pushpa.PushpaValidation@5b04476e]" started-at="2022-10-16T22:56:38Z" name="pushpaValidationWithoutModifications" finished-at="2022-10-16T22:56:54Z" duration-ms="16132" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [December 17, 2021 (United States)] but found [17 December 2021]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [December 17, 2021 (United States)] but found [17 December 2021]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at pushpa.PushpaValidation.pushpaValidationWithoutModifications(PushpaValidation.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pushpaValidationWithoutModifications -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:pushpa.PushpaValidation@5b04476e]" started-at="2022-10-16T22:56:54Z" name="tearDown" finished-at="2022-10-16T22:56:54Z" duration-ms="164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pushpa.PushpaValidation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
